name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    uses: luxass/shared-workflows/.github/workflows/ci.yaml@v0.3.0 # x-release-please-version
