name: Release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: luxass/shared-workflows/.github/workflows/reusable-release-npm.yaml@v0.4.4 # x-release-please-version
    secrets: inherit
