name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  test:
    uses: luxass/shared-workflows/.github/workflows/test.yaml@v0.3.2 # x-release-please-version
